export default {
  logo: require('@/Assets/Images/logo.jpeg'),
  email: require('@/Assets/Images/email.png'),
  lock: require('@/Assets/Images/lock.png'),
  show: require('@/Assets/Images/invisible.png'),
  hide: require('@/Assets/Images/view.png'),
  avatar: require('@/Assets/Images/profile.png'),
  driver: require('@/Assets/Images/driver.png'),
  user: require('@/Assets/Images/user.png'),
  id: require('@/Assets/Images/id-card.png'),
  logout: require('@/Assets/Images/logout.png'),
  home: require('@/Assets/Images/home.png'),
  req: require('@/Assets/Images/req.png'),
  jazz: require('@/Assets/Images/jazz.jpg'),
  easypaisa: require('@/Assets/Images/easypaisa.png'),
  card: require('@/Assets/Images/card.png'),
  paypal: require('@/Assets/Images/pay.png'),
  phone: require('@/Assets/Images/phone.png'),
  bank: require('@/Assets/Images/bank.png'),
  cvc: require('@/Assets/Images/cvc.png'),
  money: require('@/Assets/Images/money.png'),
  donation: require('@/Assets/Images/heart.png'),
}
